
services:

  # Contenedor de la aplicación (PHP + Laravel)
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: stock-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
        - .:/var/www:delegated
    #   - .:/var/www
    networks:
      - stock-net
    depends_on:
      - db

  # Servidor web (Nginx)
  nginx:
    image: nginx:alpine
    container_name: stock-nginx
    restart: unless-stopped
    ports:
      - "8000:80"               
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - stock-net
    depends_on:
      - app

  # Base de datos (MySQL)
  db:
    image: mysql:8.0
    container_name: stock-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stock_system_laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - stock-net
    ports:
      - "33060:3306" 

networks:
  stock-net:
    driver: bridge

volumes:
  dbdata: